on:
  pull_request:
    branches:
      - main
  push:
    - !main
  workflow_dispatch:

jobs:
  deploy:
    name: App CI
    runs-on:
      - ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Node Setup
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Resolve Project Dependencies Using Npm
        shell: bash
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present