on:
  pull_request:
    paths-ignore:
      - "**/*.md"
    branches:
      - main
  push:
    paths-ignore:
      - "**/*.md"
    branches-ignore:
      - main
  workflow_dispatch:

name: App CI

jobs:
  deploy:
    name: App CI
    runs-on:
      - ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Node setup
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Yarn install
        shell: bash
        run: |
          yarn install