on:
  push:
    paths-ignore:
      - "**/*.md"
    branches:
      - main
  workflow_dispatch:

name: Deploy

concurrency:
  group: terraform

env:
  AZURE_FUNCTION_APP_NAME: github-branch-protection-service
  APP_PACKAGE_PATH: .

jobs:
  infra-deploy:
    name: Terraform apply
    runs-on:
      - ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Terraform apply
        run: |
          set -o pipefail
          terraform init
          terraform apply -auto-approve
        id: apply
        working-directory: tf
        env:
          GITHUB_TOKEN:  ${{ secrets.ORG_HOOK_PAT }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          TF_VAR_github_webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
          TF_VAR_github_enforcer_pat: ${{ secrets.ENFORCER_PAT }}
          TF_VAR_function_app_name: ${{ env.AZURE_FUNCTION_APP_NAME }}

  app-deploy:
    name: App deploy
    needs: infra-deploy
    runs-on:
      - ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Node setup
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Yarn install
        shell: bash
        run: |
          yarn install

      - name: Login via Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_RBAC_CREDENTIALS }}

      - name: Deploy to function app
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ${{ env.AZURE_FUNCTION_APP_NAME }}
          package: ./${{ env.APP_PACKAGE_PATH }}