on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  apply:
    name: Terraform Apply
    runs-on:
      - ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Terraform Apply
        run: |
          set -o pipefail
          terraform init
          terraform apply -auto-approve
        id: apply
        working-directory: tf
        env:
          GITHUB_TOKEN:  ${{ secrets.ORG_HOOK_PAT }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          TF_VAR_github_webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
          TF_VAR_github_enforcer_pat: ${{ secrets.ENFORCER_PAT }}
