on:
  pull_request:
    paths-ignore:
      - "**/*.md"
    branches:
      - main
  workflow_dispatch:

name: Terraform Plan

concurrency:
  group: terraform

env:
    AZURE_FUNCTION_APP_NAME: github-branch-protection-service

jobs:
  validate:
    name: "Terraform fmt & validate"
    runs-on:
      - ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Terraform fmt check
        run: terraform fmt -check -recursive -diff

      - name: Terraform validate
        run: |
          terraform init
          terraform validate
        working-directory: tf
        env:
          GITHUB_TOKEN:  ${{ secrets.ORG_HOOK_PAT }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          TF_VAR_github_webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
          TF_VAR_github_enforcer_pat: ${{ secrets.ENFORCER_PAT }}
          TF_VAR_function_app_name: ${{ env.AZURE_FUNCTION_APP_NAME }}

  plan:
    name: Terraform plan
    runs-on:
      - ubuntu-latest
    needs: validate
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Terraform plan
        run: |
          set -o pipefail
          terraform init
          terraform plan | tee plan.txt
          if [ grep -q "Plan:" plan.txt ];then
            grep "Plan:" plan.txt > summary.txt
            echo "TF_PLAN_HAS_CHANGES=true" >> $GITHUB_ENV
          fi
        id: plan
        working-directory: tf
        env:
          GITHUB_TOKEN:  ${{ secrets.ORG_HOOK_PAT }}
          ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
          ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
          TF_VAR_github_webhook_secret: ${{ secrets.WEBHOOK_SECRET }}
          TF_VAR_github_enforcer_pat: ${{ secrets.ENFORCER_PAT }}
          TF_VAR_function_app_name: ${{ env.AZURE_FUNCTION_APP_NAME }}

      - name: Comment on pull request
        uses: actions/github-script@v3
        if: ${{ env.TF_PLAN_HAS_CHANGES }}
        with:
          script: |
            const fs = require('fs');
            const color_code_regex = /[\u001b\u009b][[()#;?]*(?:[0-9]{1,4}(?:;[0-9]{0,4})*)?[0-9A-ORZcf-nqry=><]/g;

            var summary = fs.readFileSync('tf/summary.txt').toString().replace(color_code_regex, '');
            var plan = fs.readFileSync('tf/plan.txt').toString().replace(color_code_regex, '');

            if(plan.length > 65000){
              plan = `Plan too long, truncating:\n...\n${plan.slice(-65000)}`;
            }

            const output = `
            #### Terraform Plan \`${{ steps.plan.outcome }}\`
            <details><summary>${summary}</summary>

            \`\`\`
            ${plan}
            \`\`\`
            </details>`;
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
        
